services:
    ADS\Bundle\ApiPlatformEventEngineBundle\Config:
        arguments:
            - '@ADS\Bundle\EventEngineBundle\Config'
            - '@event_engine.cache'
    ADS\Bundle\ApiPlatformEventEngineBundle\Message\Finder:
        arguments:
            - '@ADS\Bundle\ApiPlatformEventEngineBundle\Config'
    ADS\Bundle\ApiPlatformEventEngineBundle\Persister\CommandPersister:
        arguments:
            - '@EventEngine\EventEngine'
        tags:
            - 'api_platform.data_persister'
    ADS\Bundle\ApiPlatformEventEngineBundle\PropertyExtractor\PropertyStateExtractor:
        arguments:
            - '@api_platform.property_info'
        tags:
            - 'property_info.list_extractor'
            - 'property_info.type_extractor'
    ADS\Bundle\ApiPlatformEventEngineBundle\Provider\DocumentStoreCollectionDataProvider:
        arguments:
            - '@ADS\Bundle\ApiPlatformEventEngineBundle\Serializer\MessageNormalizer'
            - '@EventEngine\EventEngine'
        tags:
            - 'api_platform.collection_data_provider'
    ADS\Bundle\ApiPlatformEventEngineBundle\Provider\DocumentStoreItemDataProvider:
        arguments:
            - '@ADS\Bundle\ApiPlatformEventEngineBundle\Serializer\MessageNormalizer'
            - '@EventEngine\EventEngine'
        tags:
            - 'api_platform.item_data_provider'
    ADS\Bundle\ApiPlatformEventEngineBundle\ResourceMetaDataFactory\ShortNameResourceMetaDataFactory:
        decorates: 'api_platform.metadata.resource.metadata_factory.short_name'
        arguments:
            - '@ADS\Bundle\ApiPlatformEventEngineBundle\ResourceMetaDataFactory\ShortNameResourceMetaDataFactory.inner'
    ADS\Bundle\ApiPlatformEventEngineBundle\ResourceMetaDataFactory\MessageResourceMetaDataFactory:
        decorates: 'api_platform.metadata.resource.metadata_factory.operation'
        arguments:
            - '@ADS\Bundle\ApiPlatformEventEngineBundle\ResourceMetaDataFactory\MessageResourceMetaDataFactory.inner'
            - '@ADS\Bundle\ApiPlatformEventEngineBundle\Config'
    ADS\Bundle\ApiPlatformEventEngineBundle\Serializer\MessageNormalizer:
        decorates: 'api_platform.serializer.normalizer.item'
        arguments:
            - '@ADS\Bundle\ApiPlatformEventEngineBundle\Serializer\MessageNormalizer.inner'
            - '@ADS\Bundle\ApiPlatformEventEngineBundle\Message\Finder'
            - '@=service("EventEngine\\EventEngine").messageFactory()'
    ADS\Bundle\ApiPlatformEventEngineBundle\SchemaFactory\MessageSchemaFactory:
        decorates: 'api_platform.json_schema.schema_factory'
        arguments:
            - '@ADS\Bundle\ApiPlatformEventEngineBundle\SchemaFactory\MessageSchemaFactory.inner'
            - '@ADS\Bundle\ApiPlatformEventEngineBundle\Message\Finder'
